### ISSUE TITLE
Drywallow Daggermaw and all Firemane dragonkin (Scouts, Ash Tail...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7298]
> Drywallow Daggermaw and all Firemane dragonkin (Scouts, Ash Tails, Scalebanes,etc) are not flagged as elite mobs as per 1.12.1 WoW

.go xyz -4391.160000 -3041.420000 40.213500 1 0.807400

**Comment by Shadownflame** [comment]
- [ ] Same consideration as the dragons in Swamp of Sorrows - either mark them as elite or properly reduce their stats to be nonelites depending on which version epoch prefers. 
NPC IDs:
4331, 4329, 4334, 4328 (firemane)
4324, 4323 (searing)
4345 (croc)

- [ ] Also these two are not patrolling as they should 
![WoWScrnShot_072124_020956](https://github.com/user-attachments/assets/fcbc4491-e54b-4035-9ca5-80d133e771d9)
- [ ] And there is indeed one croc under ground in this spot, imp set to aggressive can dig it up from the soil with a firebolt:
![WoWScrnShot_072124_021333](https://github.com/user-attachments/assets/4827a588-b6c6-4458-8c6f-e9238e6c4cb0)

**Comment by Shadownflame** [comment]
[Bubbling Swamp Oozes](https://www.wowhead.com/classic/npc=4394/bubbling-swamp-ooze) are marked as elite and behave as elite, if every other mob in the area gets nerfed to nonelite, these should too

**Comment by T1ti** [comment]
If most of the new quest in the zone are non elite I would recommend keeping them elite.
It's an easy way to shake things up and refresh the experience from the 1.12 stuff people are used to, and dragons being elite and dangerous at low level is more fitting.
And they were elite for 99% of vanilla until the very last patch, seems silly to keep the last patch simplifications

**Comment by Shadownflame** [comment]
There is an issue with the new mage portal quest targeting these crocs for just one faction. So keeping these crocs elite would mean horde mages have to solo elites to get their portal while ally mages get to kill some easy nonelites. That's a terrible mismatch which would have to be corrected. Lots of other options of course, redirect the horde quest to different mobs, or the ally ones to kill elites too, it's all Dev choice, it's just something to consider.

**Comment by T1ti** [comment]
This should definitely be high prio

**Comment by dh-harald** [comment]
Searing Hatchlings, Searing Whelps are the same. Based on Wowhead they have about 3x HP, they hit like a truck, identified as non elite, and gave us non-elite XP. For a non elite quest.
