### ISSUE TITLE
There is visual bug with Rookies Bow.. it stands on left shoulde...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8038]
> There is visual bug with Rookies Bow.. it stands on left shoulder, not on back

.go xyz 77.570200 -1641.720000 92.591800 1 3.694890

**Comment by Shadownflame** [comment]
To be fair, other bows just get sheathed to another dimension. I'm not sure why this one doesn't. It looks weird.

**Comment by zana244** [comment]
Adding other custom bows/crossbows/guns which have the wrong animation/sheathing ...
All of the PvP bows behave the same way I think -- Soldier/Aspirant/Rookie.

**Comment by Shadownflame** [comment]
- [ ] Custom Gun animation: Aspirant's Rifle (61736) - held wrong, attacking wrong - as if it was a bow. Sheathing with Z looks okay.
Other IDs I could find and confirm: Rookie's Rifle (61307), Soldier's Rifle (63725), Erlgadin Family Rifle (62793), Combatant's Rifle (61430), Skirmisher's Rifle (61372)
![WoWScrnShot_071624_005019](https://github.com/user-attachments/assets/bd3eaa22-a8c3-4429-8baf-b762d46517aa)
- [ ] Custom Crossbow animation - Aspirant's Crossbow (61738) - character holds it properly when not attacking, but attack animation is that of a bow, sheating with Z makes it puncture your character's body or in case of the non-PVP ones, hangs by your legs as if it was a sword
Other IDs I could find and confirm: Rookie's Crossbow (61309), Skirmisher's Crossbow (61374), Forgotten Crossbow (60951), Forsaken Crossbow (60952), Combatant's Crossbow (61432), Soldier's Crossbow (63727), Ancident Erlgadin Crossbow (62794), Relic Hunter Crossbow (63557)
![WoWScrnShot_071624_005435](https://github.com/user-attachments/assets/aa77e96d-67bc-4ac8-9119-46f0ac41c306)
![WoWScrnShot_071624_005252](https://github.com/user-attachments/assets/1372749e-b305-482b-8083-a66cd7c3976f)
![WoWScrnShot_071624_011746](https://github.com/user-attachments/assets/2e048dad-922f-4bfb-b14b-34b63bac2297)
- [ ] Custom Bow - animation checks out when holding and attacking, some issues when sheathing - instead of disappearing or sitting on the back, pve ones sit on your shoulder like a shopping bag, while the pvp ones are a bit too high above your shoulder as if they were floating:
Houndmaster's Bow (61053), Ashyla's Longbow (61777), Blackmaw Bow (63554), Wintersun Bow (63103)
![WoWScrnShot_071624_011814](https://github.com/user-attachments/assets/920e2a39-f014-4ace-9390-e97b5decacc8)
Rookie/Aspirant/Skirmisher/Combatant/Soldier's Bow (61308,61373,61737,63727,61431), Distant Darter (61288)
![WoWScrnShot_071624_012517](https://github.com/user-attachments/assets/4c35f4e7-1c66-41f4-9005-78a106edcd07)
- [ ] Well-loved Bow (63588) is namely a bow, but looks and is classified as a crossbow? Uses bow animations and sheaths as a melee weapon
Custom thrown weapons require testing too.

**Comment by Shadownflame** [comment]
There are improvements. Most ranged weapons now animate fitting their weapon type. However, there is an issue with the animation breaking between 2 attacks, after every projectile shot, the weapon teleports back onto sheathed position on your shoulder or belt or disappears (for those which aren't shown when sheathed), and then reappears 2sec later when your next shot is due to cast. From what I can tell, this now happens to non-custom ranged weapons too.
