### ISSUE TITLE
several combat bugs on brd

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8095]
> several combat bugs on brd

.go xyz 1386.610000 -708.053000 -92.138000 736 5.056950

**Comment by Shadownflame** [comment]
Linking here every instance of combat stuck in BRD.

- [x] 1) Magmus room after engaging boss (confirmed - probably from the fire which doesn't stop)
- [x] 2) After arena (cannot reproduce - might depend on which boss you get)
- [ ] 3) The Lyceum (cannot reproduce - probably cuz the mobs are missing right now)
- [x] 4) Hurley's Cronies (confirmed, separate issue with RP)
- [x] 5) Warbringer Constructs in Hall of Crafting near Fineous (confirmed - unattackable mobs)
- [x] 6) Emperor room Ambassadors (confirmed - unattackable mobs)
- [ ] 7) Bael'gar room (unconfirmed)
- [x] 8) The Vault room - Warbringer Constructs enter combat upon looting the Dark Coffer, but do not engage (confirmed)

**Comment by kaytotes** [comment]
All of the ones that could be replicated were resolved in last deploy. State testing.

**Comment by Bennylavaa** [comment]
seems fixed
