### ISSUE TITLE
Instance: Stratholme

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8297]
This is a central housing for as many gameplay / technical issues as possible in Stratholme. Since this is a key max level dungeon it needs to be of the highest quality.

**Reported Issues**

- [x] Instance Data not saved at all, this basically bricks the instance if a restart occurs.
- [x] Door at the end of stratholme to rivendare doesn't open.
- [x] After killing Baron Rivendare in Stratholme, the door to his crypt stays shut locking you inside the boss room.
- [x] At the slaughter house square, when i summon the betah beetle pet, the gates do a stutter and almost close as if to start the encounter
- [x] Timmy the Cruel can not spawn often.
- [x] When he does spawn Timmy has no pathing.
- [x] Both gates for the abomination gauntlet inside stratholme close, general issues with their state. 
- [x] As above basically every other door state is wonky too.
- [x] Ramstein was also already spawned before we even entered the room. He can also spawn twice.
- [x] Barthilas did not run to the undead side of Stratholme upon the service gate being opened like he is supposed to.
- [x] Stratholme: Service Gate achievement is listed under Raids, and not Dungeons
- [x] baroness boss in ud strat, when she does the mind control, the player does not move or anything
- [x] Canonmaster's canons in Strat live didnt do damage/dont work as intended, in general fight buggy.
- [x] Crimson Rifleman don't attack and can't be hit by cannons
- [x] the post that points to elders square in strat undead is disconnected from the post it is supposed to be attached to
- [x] Quest Aurius' Reckoning - (5125) isn't implemented. See https://github.com/Project-Epoch/bugtracker/issues/2410
- [x] Just ventured really quickly inside, it seems to me the Black Guard Sentries (spawned mobs before baron rivendare) do not have the epoch elite modifier for hp (probably missing for damage too). 6891 hp on wowhead, 6891 hp on Epoch, considerably lower than the other trash mobs.
- [x] It looks like the Ghostly Citizens do not reset when you dance with them if you pull them (should reset them just once and they should dance back with you) https://youtube.com/shorts/aN8SnZCCEdc?si=XRxWsW4KdSkKeXc9 I understand this video is newer wow but it worked the same way in classic as well as 1.12.1
- [x] Cadaver Worms (91101) debuff from Mangled Cadavers (10382) should not stack with itself and instead behave like every other NPC debuff - after one application, the enemies hold on to further casts until the effect expires or is dispelled.
- [x] A different version of this spell (91099) is incorrectly cast by Ravaged Cadavers (10381), which also stacks up. This mob should not have this debuff in their skillset at all, they have different abilities.
- [x] Broken Cadavers (10383) spawned by the Ravaged Cadavers don't engage upon spawning.
- [x] The Restless Souls quest (5282) is not possible to complete, see report #1609 
- [x] Skeletal Guardians (10390) are casting their first Frostbolt (9672) spell with increased haste somehow, it is only 1sec cast while all subsequent casts are 3sec long as intended. Note, the two different cast-time frostbolts also apply two different slow effects which currently stack (IDs 91103, 91106)
- [ ] The three lurking Eye of Naxxramas spawns (10411) are idle and will not alert to the "intruders" when they get in proximity of the player group. Using AOE abilities while fighting enemies has a chance of getting them out of invisibility if they happen to pass by, but otherwise they are ignoring your presence and not doing their duty as alarm bots. The only exception seems to be if a warlock casts Detect Invisibility, which somehow prompts them to react. Dynamic spawns that occur very seldom while fighting mobs seem to be working fine but you'll meet one of those in every 10th dungeon on average. 
+ might wanna consider upping their health from the current 400 to the prenerf 1-1.5k value as well (suggestion)
Note: the idle lurkers are responsible for some combat bugs, seems to happen if the lurker is on top of a group of enemies when the players pull them (they probably get some peer aggro but they are just put in combat and still don't engage), then if the AOE doesn't get him out of invis, after finishing the pack the player will be in combat until the Eye is found and killed (either with warlock detect invis, mage invis, or spamming AOE randomly until you catch him since the bastard wont engage)
- [x] Undead Postman spawns (ID 11142) don't seem to receive epoch buffing, they have the same health as on retail. They also have terrible pathing issues, most of the time they seem to be rooted around their mailbox.
- [x] Crimson Conjuror (10419) Summoned Water Elemental (10955) won't assist the caster, won't engage at all unless you step next to them for proximity aggro. They can also be summoned multiple times on top of each other, which looks a little wonky - I believe the caster should not attempt to summon another until the first one is killed.
- [x] Cannon master Willey (10997) encounter mechanics now work on paper, the cannons can fire and deal damage and the Crimson Riflemen (11054) position and attack behavior is blizzlike. Issue is, It takes 4 or 5 cannons fired to kill one wave of Riflemen - basically every single cannonball around the boss. This is most certainly due to the ridiculous fire resistance these mobs possess: they are resisting about 75-90% of every cannonball's fire damage. This makes using the cannons a waste of time and energy. Without the resistances, the cannon damage would be *almost* enough to kill the wave like it's supposed to: the cannon damage seems to be a flat 3k, while the Riflemen have 3052 health. This might be a rounding issue, I believe the two are supposed to match, because on blizz the cannons oneshot adds.
- [x] There is still a hole in the wooden direction pole of undead side, one sign is just floating (Fixed upstream, will naturally fix here eventually)
![WoWScrnShot_071024_202605](https://github.com/Project-Epoch/bugtracker/assets/172074323/5c949c58-96bd-46da-ae3b-682ed0b9a1c6)
- [x] Nerubian enemies drop Crypt Fiend Parts (22525) which are currently of no use and cannot be vendored either. Suggest removing them for now (suggestion)
- [x] Baron's Ultimatum debuff disappears when players die, losing track of the baron run timer. Should persist through death. Seems to be lost upon zoning in /out too, this is also not convenient. (Suggestion) 
Baron also applies a new, different ID debuff at the 10min, 5min, and 1min marks (every time he does a /yell RP), all of which stack with each other, looks a bit weird. spell IDs 27861, 27863, 27864, 27865
![WoWScrnShot_071024_211929](https://github.com/Project-Epoch/bugtracker/assets/172074323/128394a5-5b16-4781-a4b3-857d44cc8f2d)
- [ ] Line of Sight issue in Balnazzar room, the tiles on his floor just give los
![WoWScrnShot_071124_005031](https://github.com/Project-Epoch/bugtracker/assets/172074323/45e09465-c04f-40af-aeb9-6407b57ef74f)
- [x] Bile Spewers (10416) spawn too many bile slimes (10697) and too frequently, it's like 5-6 slimes every 5-6seconds, overwhelming. The auto-engage script of the abominations in the room is also very random, sometimes 3 of them come to the group at once, and if you wipe or reset, they will not reset their positions. The slimes also don't despawn if the group wipes, so you will face 25-30 of them on the next attempt.
- [x] Baroness Anastari's (10436) MC spell (17246) is still broken, perhaps worse than it was. The MC'd target is still not moving or attacking, but now there is also an issue where the MC'd target loses sight of the other players while MC'd, and if the only person still alive is the MC, the boss doesn't reset and you have to wait out the 2min timer while stuck in MC.
- [x] Ramstein's auto attack hits harder than Ortorg's and his hook oneshots cloth players in adequate gear (we only survived on the beta because of the t0.5)
- [x] Aurius' Reckoning (5125) is now implemented, but the quest Medallion of Faith (5122) is not currently repeatable, locking players out of the follow up if they cannot kill Baron in the same ID
- [x] Aurius' Reckoning cannot be completed if Aurius (10917) dies during the Baron encounter, which is not intended. Aurius dies during the fight by design, his survival should not be a requirement, only killing Baron.

**Comment by Shadownflame** [comment]
- [x] Ramstein's Knockout (93212) doesn't obey diminishing returns and stuns the player for 6sec every 10seconds (tank spends 60% of time stunned). It seems also more frequent than he uses it on classic videos (seems to be every 15-16sec).

**Comment by Shadownflame** [comment]
-Cadaver debuff fixed no longer stacks.
-Mages no longer start with a hasted cast.
-Broken cadavers now engage properly.
-Restless souls quest now works as intended. ghostly citizens properly de-aggro if you /dance with them, for the first time.
-Sentries receive buffing as intended.
-Ramstein's damage is slightly nerfed and his hook damage is much more manageable. He is still very challenging for a low geared party as intended.
-Summoned water elementals now engage.
-Crypt fiend parts no longer in nerubian loot table.
-Abominations now aggro less frequently and the group has a chance to cut ahead and get out of combat. Bile spewers seldom spawn 1-1 slime and only spawn the big group upon death.
-Cannon damage greatly increased, and mobs no longer resist damage. Guaranteed to 1 shot adds.
-Baron's ultimatum reworked: now persists when leaving the dungeon and reapplies whenever players re-enter the dungeon if the Baron run is still going (if the players are alive when they re enter). A ghost rezzing inside stratholme won't get the debuff and death still removes it, this is not possible to fix as per ktotes. No longer shows a timer, players have to pay attention to the RP.
-There seems to be some improvement on the ID, after 2hours passed I am still in the same ID 15 as before, the scarlet door closed back but the mobs didn't respawn. After forced restart the trash respawned in this specific wing (not the UD side I cleared recently), but the boss I killed in scarlet (willey) did not respawn.

**Comment by Shadownflame** [comment]
- [x] Postmen now receive epoch buffing, but are still rooted around their mailbox.
- [x] Found a terrible glitch with the UD side door that happens if you enter from the Service Gate and Magistrate runs through and opens the door for you. It leaves the door in a state where it is still clickable:
![WoWScrnShot_072424_050709](https://github.com/user-attachments/assets/a2f15d95-d1bd-4596-b006-2b833161c3ad)
If someone who has the key accidentally clicks it, the gate closes for good, locking players in/out, becomes unclickable in closed state:
![WoWScrnShot_072424_050718](https://github.com/user-attachments/assets/948fcda1-dc63-40cc-920a-730b0d17d37c)

This can happen to both doors on that corridor.

**Comment by Shadownflame** [comment]
- [x] Baron's Ultimatum doesn't properly reapply when Baron does RP at 10-5-1minutes left, if the players had previously lost their debuff to dying.
- [x] Issue with abomination event not properly reseting after wipe. The aboms you are fighting now reset and return to their spots and Bile Slimes despawn as intended, however the "next abom in queue" won't disengage and walks up to this spot to sit (may catch the group trying to rezz up there)
![WoWScrnShot_072424_180313](https://github.com/user-attachments/assets/ee54b712-2474-4b0a-8317-581709551c78)
- [x] Black Guard Sentries can be still aggroed separately if you pull one on the side

**Comment by Bennylavaa** [comment]
Crimson Initiate spams spells

**Comment by kaytotes** [comment]
Removing both launch blocking and high prio from the Stratholme epic. Next deploy fixes the things remaining I actually cared about.
