### ISSUE TITLE
Pathing issues collected

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8302]
This is the main report to gather the countless reports of NPC pathing issues (mobs and pets) that the Devs are already aware of and will have to fix collectively.

Major points:

- [ ] wonky pathing, making needless movements
- [ ] terrain causing NPC to change direction despite nothing visible in path
- [x] terrain causing pet to get trapped in one spot
- [ ] choosing unnecessary long path to get to destination
- [ ] clipping into floor, wall, texture
- [ ] movement speed altercations
- [ ] unable to move to certain locations that should be possible to reach 
- [ ] evading and/or resetting immediately in certain positions
- [ ] when following a moving target, major delay in adjusting their direction
- [ ] underwater mobs not moving properly or at all
- [ ] other interactions with water (not properly animating or completely ignoring the expected water behaviour, wrong speed, wrong direction)
- [x] evade behavior when player touches water / jumps in water

Confirmed spots to reproduce (to be extended):
.go xyz -5418.610000 3652.350000 8.144990 1 2.879100 (resolved)
https://github.com/user-attachments/assets/7a66ffa5-cfc1-4661-bd49-1ab23ddd3344
.go xyz 2232.770000 -6433.120000 4.334740 1 4.645740 (resolved)
https://github.com/user-attachments/assets/8ef1705e-f2d5-4af1-98be-a0ed446a8938
.go xyz -14705.800000 454.975000 0.134452 0 4.507630 Rippa - (14490)
.go xyz -4523.230000 2036.160000 50.025200 1 0.251149 Deep Woods Moth
.go xyz 339.438000 -3766.940000 106.793000 0 0.210789 Direglob
.go xyz -23.089100 -5223.800000 -2.326190 1 0.256430 Kul tiras
.go xyz 89.865000 -2813.870000 115.675000 0 0.761440 - Vilebranch climbing structures
.go xyz -9891.340000 440.969000 34.757400 0 1.781920 Stonetusk boar
.go xyz -704.346000 -2056.610000 65.490600 1 5.362860 Deviate
.go xyz 4570.710000 362.964000 33.491700 1 3.041340 Twilight thug
.go xyz -679.745000 -2048.250000 65.888500 1 5.902280 Devouring Ectoplasm
.go xyz -2822.740000 -1003.460000 -1.045030 0 1.219180 Cursed Marine
.go xyz -741.744000 -3766.960000 232.378000 0 3.445070 Vilebranch Aman'zasi
.go xyz -576.936000 207.601000 -128.070000 725 4.548040! Deadmines in water [image](https://github.com/user-attachments/assets/0368d6e7-ed4d-40cb-94a0-5c704bd7c589)
.go xyz -632.227000 179.534000 -85.954300 725 3.707180 Deadmines near ramps
.go xyz -7646.120000 -2143.290000 -271.363000 1 2.096310 Glitched spot, any nearby mob gets confused
https://github.com/user-attachments/assets/76f3a407-59d7-4a01-a0fb-6170a627ab9f
.go xyz 8673.270000 884.747000 22.448700 1 1.055840 Darnassus 
https://github.com/user-attachments/assets/0d8d4ada-ca9c-4644-ad67-a7e7000aceae

**Comment by Shadownflame** [comment]
Major improvements to pets follow behavior, NPC evade behavior, and NPC behavior in or around water.
Chase behavior unchanged so far.

**Comment by Shadownflame** [comment]
Improvements on some mobs that earlier hard-evaded in their position such as ID 4014. 
Now it is possible to engage them despite there not being a perfect path for them to reach you. Issue is, when the player resets combat (outrange, death, feign, whatever), the mobs don't know how to find their way back to their original spawn point. There is no path, clearly, so they just stop and stay wherever they are when the player drops combat (or whatever is the closest they can path up). 
This creates weird piles of enemies like this:
![image](https://github.com/user-attachments/assets/7c8ce151-f159-4b63-9594-381ceed926d0)
(Note, Arugal behaves the same way in SFK and thus often gets stuck on the balcony after a reset)
The other noteworthy spot is outside WC where was earlier impossible to engage certain mobs. Now they work fine if you pull them from solid ground, still evade bugging if you are in the ankle-deep water (both SS shows the same raptor):
![WoWScrnShot_082324_232418](https://github.com/user-attachments/assets/8d00bdd3-f8dc-402b-bd37-64db19bbc503)
![WoWScrnShot_082324_232153](https://github.com/user-attachments/assets/78adab8f-2628-4ffc-b50f-58c971dd4904)

**Comment by Shadownflame** [comment]
Adding here that several NPCs involved in quests run through terrain and walls without any kind of attempt for proper pathing. These are 99% cosmetic issues that don't interfere with the quest completion.
