### ISSUE TITLE
Instance: Sunken Temple

### ISSUE THREAD

**Issue by zana244** [Project-Epoch/bugtracker#8310]
Collection of issues related to the Sunken Temple dungeon.

1. Morphaz and Hazzas instantly despawn upon death, losing all their loot. Needed for some class quests.
2. There is no shield blocking Jammal'an, so he can be attacked/killed without killing the 6 minibosses. He also does his RP "The shield be down! Rise up Atal'Ai! Rise Up!" when you approach him, when he should be doing it after the 6 minibosses die.
3. Unsure on this, but I think the whole room should aggro when Jammal'an gets aggroed, requiring it to be cleared. On Epoch you can solo pull Jammal'an and nobody gets pulled (apart from his add).

~~4. There is no shield blocking Shade of Eranikus, allowing him to be attacked without killing Jammal'an.~~ Invalid - Kaytotes

5. Pulling Shade of Eranikus should aggro all of the alive dragonkin, on Epoch you can solo pull him.
6. Morphaz and Hazzas can be solo pulled, I think they are normally linked and can't be pulled separately. Same for Dreamscythe and Weaver. Dreamscythe and Weaver should be patrolling in a circle.
7. There are some reports of the drakes not spawning or despawning after some time, I also encountered it but need to find a way to reproduce.

~~8. There are no doors on Egg of Hakkar event (Unconfirmed).~~ Invalid - Kaytotes

9. Some reports mention that summoning Avatar of Hakkar does not work (even with 4 pedestals of blood -- btw the object is called PedAstal ingame, probably a typo) Again unconfirmed, this might be some TBC behaviour, in vanilla you the mobs just start spawning.
10. Avatar of Hakkar can be summoned multiple times (Unconfirmed)

https://www.youtube.com/watch?v=VGtKRUTk8WA

**Comment by Shadownflame** [comment]
Adding this here, killing Hakkar might be despawning drakes (needs confirm).

**Comment by kaytotes** [comment]
Next deploy fixes basically all valid reports except maybe 1. Setting to state testing.

**Comment by zana244** [comment]
Forgot to add, almost all dragonkin packs are unlinked, and rely solely on social aggro to link, which causes some of them to be able to be pulled separately. Possibly the same for mobs in Jammal'an's room.

**Comment by Bennylavaa** [comment]
including this here https://github.com/Project-Epoch/bugtracker/issues/763

**Comment by Shadownflame** [comment]
- [x] Hukku's Succubus (8657) does not engage when spawned. The other pets seemed fine.
- [x] ~~Hukku keeps spawning his minions repeatedly instead of just once as intended~~ Kaytotes: Not a bug.
- [ ] dragon packs in the Pit of Sacrifice are indeed unlinked and only 1 or 2 extra mob aggroes if you pull from the sides
- [x] Jammal'an's door can be bypassed with petpulling
- [x] Nightmare Scalebane (5277) is stacking 2 different versions of shield improved blocking (3639 and 3248)
![WoWScrnShot_073124_000743](https://github.com/user-attachments/assets/fe9ca51b-28e2-4237-9520-e6a0f92083cd)
- [x] Pedestals are misspelled as Pedalstals still
- [x] Weaver/Dreamscythe aren't linked
- [x] Hazzas and Morphaz don't spawn
- [ ] Some mobs auto engage near the altar of Atalalarion, under investigation

**Comment by Shadownflame** [comment]
Hazzas and Morphaz now spawn and can be looted properly after killing.
- [x] Hazzas and Morphaz aren't linked and can be pulled separately
- [x] Engaging Eranikus doesn't properly pull remaining dragonkin in the instance (it pulls like 2 packs and that's it)
- [x] Eranikus' new custom adds and portals don't despawn when the fight ends
- [x] Eranikus' new tailswipe has an insane range and angle, it fits a much bigger dragon

**Comment by kaytotes** [comment]
Remaining issues are minor or unconfirmed. Downgrading.

**Comment by Shadownflame** [comment]
Above issues largely seem resolved. 

Eranikus has a new critical issue:
Wiping on the fight keeps adding to the number of adds he summons on the next try. He starts with 3 adds from the portals on first attempt, which is doable, second attempt he will spawn 6, then 9, etc...
If you wiped more than once the fight is practically bricked.

The other feature that requires revision is the Pedestal summoning for Avatar of Hakkar. It takes way, way too long even for 4 people channeling at once to begin the fight and it is taxing due to losing health from the ritual, so many people just assume it's broken and move on. The time frame needs to be cut shorter and there needs to be some kind of visual indicator to the long channel doing something. An emote periodically or appropriate graphic effects would do.
